# Generated by Django 3.0.8 on 2020-07-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency_id',
        ),
    ]
